---
- name: Configure Web Server
  hosts: webservers
  become: yes
  roles:
    - common
    - apache
    - php

- name: Configure Database Server
  hosts: dbservers
  become: yes
  roles:
    - common
    - mysql
